apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-deployment
  labels:
    app: login-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: login-deployment
  template:
    metadata:
      labels:
        app: login-deployment
    spec:
      containers:
        - name: login-container
          image: hamidbong/login-service:{{BUILD_NUMBER}}
          ports:
            - containerPort: 5000
