apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-service-node
  labels:
    app: deployment-service-node
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deployment-service-node
  template:
    metadata:
      labels:
        app: deployment-service-node
    spec:
      containers:
        - name: node-container
          image: hamidbong/service-node:{{BUILD_NUMBER}}
          ports:
            - containerPort: 5001
          env:
        # Configuration MongoDB
        - name: MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
        - name: URI_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: mongodb-configmap
              key: database_url
        - name: MONGODB_PORT
          value: "27017"