apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-react-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-react-deployment
  template:
    metadata:
      labels:
        app: frontend-react-deployment
    spec:
      containers:
      - name: frontend-container
        image: hamidbong/frontend-react:{{BUILD_NUMBER}}
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: dockerhub-secret
