apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-service-python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deployment-service-python
  template:
    metadata:
      labels:
        app: deployment-service-python
    spec:
      containers:
      - name: deployment-service-python
        image: hamidbong/service-python:{{BUILD_NUMBER}}
        ports:
        - containerPort: 5003
