apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-service-python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deployment-service-python
  template:
    metadata:
      labels:
        app: deployment-service-python
    spec:
      containers:
      - name: deployment-service-python
        image: hamidbong/service-python:{{BUILD_NUMBER}}
        ports:
        - containerPort: 5003
        env:
        - name: MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
        - name: URI_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: mongodb-configmap
              key: database_url
        - name: MONGODB_PORT
          value: "27017"