- name: Get join command from master
  slurp:
    src: /tmp/join-command.sh
  register: join_cmd
  delegate_to: master

- name: Join node to the cluster
  shell: "{{ join_cmd.content | b64decode }}"
  args:
    creates: /etc/kubernetes/kubelet.conf
